# Generated by Django 6.0.4 on 2026-04-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
