# Generated by Django 6.0.3 on 2026-05-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0005_add_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(default='HELPEX is an adaptive digital studio crafting exceptional digital experiences. We combine creative design, cutting-edge technology, and strategic thinking to deliver transformative solutions that drive business growth and success.'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_line_1',
            field=models.CharField(default='Innovating the Future', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_line_2',
            field=models.CharField(default='One Solution at a Time', max_length=100),
        ),
    ]
