# Generated by Django 6.0.3 on 2026-05-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0006_alter_herosection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='HELPEX BRO. All rights reserved.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtagline',
            field=models.CharField(default='One Solution at a Time', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_tagline',
            field=models.CharField(default='Innovating the Future', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_hours',
            field=models.CharField(default='Mon-Fri: 9AM - 6PM', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_about_title',
            field=models.CharField(default='About Us', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_blog_title',
            field=models.CharField(default='Latest Insights', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_clients_title',
            field=models.CharField(default='Our Clients', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_contact_title',
            field=models.CharField(default='Get In Touch', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_gallery_title',
            field=models.CharField(default='Our Gallery', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_portfolio_title',
            field=models.CharField(default='Our Portfolio', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_process_title',
            field=models.CharField(default='Our Working Process', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_services_title',
            field=models.CharField(default='Our Services', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_team_title',
            field=models.CharField(default='Our Team', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_testimonials_title',
            field=models.CharField(default='What Our Clients Say', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_github',
            field=models.URLField(blank=True),
        ),
    ]
