# Generated by Django 6.0.3 on 2026-05-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0007_sitesettings_copyright_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plan name (e.g., Basic, Pro, Enterprise)', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the plan')),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Plan price', max_digits=10)),
                ('currency', models.CharField(default='$', help_text='Currency symbol', max_length=10)),
                ('billing_period', models.CharField(default='/month', help_text='Billing period text', max_length=50)),
                ('popular_badge', models.CharField(choices=[('none', 'None'), ('popular', 'Popular'), ('best_value', 'Best Value'), ('recommended', 'Recommended')], default='none', help_text='Highlight this plan', max_length=20)),
                ('cta_text', models.CharField(default='Get Started', help_text='Call to action button text', max_length=50)),
                ('cta_url', models.CharField(blank=True, default='/contact/', help_text='CTA button URL', max_length=200)),
                ('icon_class', models.CharField(default='fa-star', help_text='FontAwesome icon class', max_length=100)),
                ('color_accent', models.CharField(default='#28A197', help_text='Accent color for this plan (hex)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Feature description', max_length=200)),
                ('included', models.BooleanField(default=True, help_text='Is this feature included in the plan?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='helpex_app.pricingplan')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['plan', 'order'],
            },
        ),
    ]
