# Generated by Django 6.0.3 on 2026-05-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0008_pricingplan_pricingfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUsReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('icon_class', models.CharField(default='fa-check-circle', help_text='FontAwesome icon class', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Reason',
                'verbose_name_plural': 'Why Choose Us Reasons',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Choose Us', max_length=200)),
                ('subtitle', models.TextField(blank=True, default='Discover what makes us the perfect partner for your digital success')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
                'verbose_name_plural': 'Why Choose Us Section',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('icon_class', models.CharField(default='fa-trophy', help_text='FontAwesome icon class', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Stat',
                'verbose_name_plural': 'Why Choose Us Stats',
                'ordering': ['order', 'label'],
            },
        ),
    ]
