# Generated by Django 6.0.3 on 2026-05-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0010_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Secondary banner image', null=True, upload_to='services/banner/'),
        ),
        migrations.AddField(
            model_name='service',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='[{"question": "...", "answer": "..."}]'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "...", "description": "...", "icon": "fa-icon"}]'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Main hero banner image', null=True, upload_to='services/hero/'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_steps',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "...", "description": "..."}]'),
        ),
        migrations.AddField(
            model_name='service',
            name='starting_price',
            field=models.CharField(blank=True, help_text='e.g., $2,000', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='stats',
            field=models.JSONField(blank=True, default=list, help_text='[{"value": "100+", "label": "..."}]'),
        ),
        migrations.AddField(
            model_name='service',
            name='support',
            field=models.CharField(blank=True, help_text='e.g., 24/7 Support', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='timeline',
            field=models.CharField(blank=True, help_text='e.g., 4-8 weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='ServiceCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/case-studies/')),
                ('client', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(blank=True, help_text='e.g., 200% increase in traffic', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='helpex_app.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('caption', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='helpex_app.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
