# Generated by Django 6.0.3 on 2026-05-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0011_service_banner_image_service_faqs_service_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/carousel/')),
                ('video', models.FileField(blank=True, help_text='MP4/WebM video file', null=True, upload_to='hero/carousel/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Carousel Item',
                'verbose_name_plural': 'Hero Carousel Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
