# Generated by Django 6.0.3 on 2026-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0012_herocarouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='registered/')),
                ('description', models.CharField(blank=True, help_text='e.g., Registered with SECP', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registered Company',
                'verbose_name_plural': 'Registered Companies',
                'ordering': ['order', 'name'],
            },
        ),
    ]
