# Generated by Django 6.0.3 on 2026-05-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0013_registeredcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fa-box', help_text='FontAwesome icon class', max_length=100)),
                ('color', models.CharField(default='#4D5FF1', help_text='Category accent color (hex)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short catchy tagline', max_length=200)),
                ('description', models.TextField(help_text='Full product description')),
                ('short_description', models.CharField(blank=True, help_text='Brief summary for listing cards', max_length=300)),
                ('icon_class', models.CharField(default='fa-cube', help_text='FontAwesome icon class', max_length=100)),
                ('hero_image', models.ImageField(blank=True, help_text='Main hero banner image', null=True, upload_to='products/hero/')),
                ('logo', models.ImageField(blank=True, help_text='Product logo/icon', null=True, upload_to='products/logos/')),
                ('version', models.CharField(blank=True, help_text='e.g., v2.1.0', max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('pricing_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('freemium', 'Freemium'), ('contact', 'Contact for Pricing')], default='contact', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='$', max_length=10)),
                ('billing_period', models.CharField(blank=True, default='/month', max_length=50)),
                ('website_url', models.URLField(blank=True, help_text='Product website URL')),
                ('demo_url', models.URLField(blank=True, help_text='Live demo URL')),
                ('docs_url', models.URLField(blank=True, help_text='Documentation URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('features', models.JSONField(blank=True, default=list, help_text='[{"title": "...", "description": "...", "icon": "fa-icon"}]')),
                ('specifications', models.JSONField(blank=True, default=list, help_text='[{"label": "...", "value": "..."}]')),
                ('screenshots', models.JSONField(blank=True, default=list, help_text='Optional inline screenshot URLs (deprecated, use ProductScreenshot model)')),
                ('faqs', models.JSONField(blank=True, default=list, help_text='[{"question": "...", "answer": "..."}]')),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='Array of technologies used')),
                ('system_requirements', models.TextField(blank=True, help_text='System requirements text')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage/featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='helpex_app.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fa-check', help_text='FontAwesome icon class', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_features', to='helpex_app.product')),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Product Features',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_images', to='helpex_app.product')),
            ],
            options={
                'verbose_name': 'Product Screenshot',
                'verbose_name_plural': 'Product Screenshots',
                'ordering': ['order', 'id'],
            },
        ),
    ]
