# Generated by Django 6.0.3 on 2026-05-21 11:03

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_client_slugs(apps, schema_editor):
    Client = apps.get_model('helpex_app', 'Client')
    for client in Client.objects.all():
        if not client.slug:
            base_slug = slugify(client.name)
            slug = base_slug
            counter = 1
            while Client.objects.filter(slug=slug).exclude(pk=client.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            client.slug = slug
            client.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0014_productcategory_product_productfeature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Client Review', 'verbose_name_plural': 'Client Reviews'},
        ),
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.RunPython(populate_client_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='helpex_app.client'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='helpex_app.portfolioitem'),
        ),
    ]
