# Generated by Django 6.0.3 on 2026-06-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpex_app', '0015_alter_testimonial_options_client_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='stats_label_4',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stats_number_4',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
